path=(
  ~/bin
  ~/bin/google-cloud-sdk/bin
  ~/golang/bin
  ~/.cabal/bin
  ~/.cargo/bin
  /usr/local/bin
  /usr/local/sbin
  /usr/local/opt/node
  /usr/local/share/npm/bin
  /opt/local/USD/bin
  ~/flutter/bin
  $path
)

export LSCOLORS=exfxcxdxbxegedabagacad

export NODE_PATH=/usr/local/lib/node
export TERM=xterm-256color
# export LIBRARY_PATH="/opt/local/lib/:$LIBRARY_PATH"
export LIBRARY_PATH=""
export GOPATH=~/golang
export ANDROID_HOME=/usr/local/opt/android-sdk

export LEAF_PATH=$HOME/code
export PYTHONPATH="~/python:/opt/local/USD/lib/python:$PYTHONPATH"

if which rbenv > /dev/null; then eval "$(/usr/local/bin/rbenv init -)"; fi
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
if which direnv > /dev/null; then eval "$(direnv hook zsh)"; fi
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
